// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// decTreeImpFuncCpp
List decTreeImpFuncCpp(const int myITEM_SIZE, const int myRANK_SIZE, const int myCART_SIZE, const std::string myDATA_FILE, const std::string myINFO_FILE, const std::string myOUTPUT_FILE, const std::string mymode, const std::string myTMODE, const bool mypairwise, const bool myPW_DATA, const std::string myprediction, const int myNODE_SIZE, const int myMIN_NODE_SIZE, const int myRANK_ITEM, const double myST_ALP, const double myCHI_ALP, const double myTRAIN_PROP, const bool myCV_TEST, const int myTEST_STAGE);
RcppExport SEXP StatMethRank_decTreeImpFuncCpp(SEXP myITEM_SIZESEXP, SEXP myRANK_SIZESEXP, SEXP myCART_SIZESEXP, SEXP myDATA_FILESEXP, SEXP myINFO_FILESEXP, SEXP myOUTPUT_FILESEXP, SEXP mymodeSEXP, SEXP myTMODESEXP, SEXP mypairwiseSEXP, SEXP myPW_DATASEXP, SEXP mypredictionSEXP, SEXP myNODE_SIZESEXP, SEXP myMIN_NODE_SIZESEXP, SEXP myRANK_ITEMSEXP, SEXP myST_ALPSEXP, SEXP myCHI_ALPSEXP, SEXP myTRAIN_PROPSEXP, SEXP myCV_TESTSEXP, SEXP myTEST_STAGESEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type myITEM_SIZE(myITEM_SIZESEXP);
    Rcpp::traits::input_parameter< const int >::type myRANK_SIZE(myRANK_SIZESEXP);
    Rcpp::traits::input_parameter< const int >::type myCART_SIZE(myCART_SIZESEXP);
    Rcpp::traits::input_parameter< const std::string >::type myDATA_FILE(myDATA_FILESEXP);
    Rcpp::traits::input_parameter< const std::string >::type myINFO_FILE(myINFO_FILESEXP);
    Rcpp::traits::input_parameter< const std::string >::type myOUTPUT_FILE(myOUTPUT_FILESEXP);
    Rcpp::traits::input_parameter< const std::string >::type mymode(mymodeSEXP);
    Rcpp::traits::input_parameter< const std::string >::type myTMODE(myTMODESEXP);
    Rcpp::traits::input_parameter< const bool >::type mypairwise(mypairwiseSEXP);
    Rcpp::traits::input_parameter< const bool >::type myPW_DATA(myPW_DATASEXP);
    Rcpp::traits::input_parameter< const std::string >::type myprediction(mypredictionSEXP);
    Rcpp::traits::input_parameter< const int >::type myNODE_SIZE(myNODE_SIZESEXP);
    Rcpp::traits::input_parameter< const int >::type myMIN_NODE_SIZE(myMIN_NODE_SIZESEXP);
    Rcpp::traits::input_parameter< const int >::type myRANK_ITEM(myRANK_ITEMSEXP);
    Rcpp::traits::input_parameter< const double >::type myST_ALP(myST_ALPSEXP);
    Rcpp::traits::input_parameter< const double >::type myCHI_ALP(myCHI_ALPSEXP);
    Rcpp::traits::input_parameter< const double >::type myTRAIN_PROP(myTRAIN_PROPSEXP);
    Rcpp::traits::input_parameter< const bool >::type myCV_TEST(myCV_TESTSEXP);
    Rcpp::traits::input_parameter< const int >::type myTEST_STAGE(myTEST_STAGESEXP);
    __result = Rcpp::wrap(decTreeImpFuncCpp(myITEM_SIZE, myRANK_SIZE, myCART_SIZE, myDATA_FILE, myINFO_FILE, myOUTPUT_FILE, mymode, myTMODE, mypairwise, myPW_DATA, myprediction, myNODE_SIZE, myMIN_NODE_SIZE, myRANK_ITEM, myST_ALP, myCHI_ALP, myTRAIN_PROP, myCV_TEST, myTEST_STAGE));
    return __result;
END_RCPP
}
